name: OMAe Dispatch / run-omae

on:
  workflow_dispatch:
    inputs:
      pat:
        description: 'Personal Access Token with contents/actions/workflows:write'
        required: true
        type: string
      promote:
        description: 'Also copy candidate -> current'
        required: false
        default: "false"
        type: choice
        options: ["false","true"]

permissions:
  contents: write
  actions: write
  workflows: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build the same template Studio uses
      - name: Build landing_saas
        working-directory: templates/landing_saas
        run: |
          npm ci || npm i
          npm run build

      - name: Publish to apps/publish/candidate
        run: |
          set -euo pipefail
          rm -rf apps/publish/candidate/*
          mkdir -p apps/publish/candidate
          cp -R templates/landing_saas/dist/. apps/publish/candidate/

          # Inject correct <base> for GH Pages
          f=apps/publish/candidate/index.html
          p="/OMAE/${f%index.html}"
          awk -v base="$p" 'BEGIN{IGNORECASE=1} /<head[^>]*>/{print;print "  <base href=\"" base "\">";next} {print}' "$f" > "$f.tmp" && mv "$f.tmp" "$f"

          # Add SPA fallback
          cp "$f" apps/publish/candidate/404.html

      - name: Optionally promote candidate -> current
        if: inputs.promote == 'true'
        run: |
          set -euo pipefail
          rm -rf apps/publish/current/*
          mkdir -p apps/publish/current
          cp -R apps/publish/candidate/. apps/publish/current/

          # Fix base for current
          f=apps/publish/current/index.html
          p="/OMAE/${f%index.html}"
          awk -v base="$p" 'BEGIN{IGNORECASE=1} /<head[^>]*>/{print;print "  <base href=\"" base "\">";next} {print}' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
          cp "$f" apps/publish/current/404.html

      - name: Commit & push using PAT (bypass branch protection)
        env:
          GH_PAT: ${{ inputs.pat }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git config user.name  "omAe bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "publish: update candidate${{ inputs.promote == 'true' && ' and current' || '' }} via workflow" || echo "nothing to commit"

          # Rebase on remote and push with PAT
          git pull --rebase "https://x-access-token:${GH_PAT}@github.com/${REPO}.git" "${BRANCH}" || true
          git push "https://x-access-token:${GH_PAT}@github.com/${REPO}.git" "HEAD:${BRANCH}"
