name: OMAe Dispatch

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'site/**'
      - 'templates/**'
      - 'apps/studio/**'
      - 'playbooks/**'
      - 'executor/**'
      - '.github/workflows/omae.yml'

permissions:
  contents: write

jobs:
  run-omae:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run OMAe (non-fatal for now)
        run: |
          set -euo pipefail
          PYTHONPATH=executor python -m omae.cli -p playbooks/site_template.yaml || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build site
        working-directory: site
        run: |
          npm ci || npm i
          npm run build

      - name: Publish candidate/current (+base +404)
        shell: bash
        run: |
          set -euo pipefail
          rm -rf apps/publish/candidate/* apps/publish/current/*
          mkdir -p apps/publish/candidate apps/publish/current

          # candidate
          cp -R site/dist/. apps/publish/candidate/
          f=apps/publish/candidate/index.html
          p="/OMAE/${f%index.html}"
          awk -v base="$p" 'BEGIN{IGNORECASE=1} /<head[^>]*>/{print;print "  <base href=\"" base "\">";next} {print}' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
          cp "$f" apps/publish/candidate/404.html

          # current
          cp -R apps/publish/candidate/. apps/publish/current/
          f=apps/publish/current/index.html
          p="/OMAE/${f%index.html}"
          awk -v base="$p" 'BEGIN{IGNORECASE=1} /<head[^>]*>/{print;print "  <base href=\"" base "\">";next} {print}' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
          cp "$f" apps/publish/current/404.html

          # studio (if present)
          if [ -f apps/studio/index.html ]; then
            awk 'BEGIN{IGNORECASE=1} /<head[^>]*>/{print;print "  <base href=\"/OMAE/apps/studio/\">";next} {print}' apps/studio/index.html > apps/studio/index.html.tmp && mv apps/studio/index.html.tmp apps/studio/index.html || true
            sed -E -i 's|src="/OMAE/assets/|src="assets/|g; s|href="/OMAE/assets/|href="assets/|g' apps/studio/index.html || true
            cp apps/studio/index.html apps/studio/404.html || true
          fi

      - name: Commit & push published files
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "ci(publish): build site and update candidate/current with base+404"
          git push
