name: OMAe Dispatch (FULL-FAT)
on:
  workflow_dispatch:
    inputs:
      pipeline: { description: "Playbook key", required: true, default: "site_template" }
      prompt: { description: "High-level instructions (site_prompt)", required: false, default: "" }
      template_id: { description: "Template ID", required: false, default: "landing_saas" }
      title: { description: "Title", required: false, default: "Acme" }
      tagline: { description: "Tagline", required: false, default: "Do more, faster." }
      cta: { description: "CTA", required: false, default: "Get Started" }
      url: { description: "Source URL", required: false, default: "https://example.com" }
jobs:
  run-omae:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install executor deps
        run: |
          # cd executor (run from repo root)
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run executor
        env:
          OMAE_TEMPLATE_ID: ${{ github.event.inputs.template_id }}
          OMAE_TITLE: ${{ github.event.inputs.title }}
          OMAE_TAGLINE: ${{ github.event.inputs.tagline }}
          OMAE_CTA: ${{ github.event.inputs.cta }}
          OMAE_URL: ${{ github.event.inputs.url }}
          OMAE_PROMPT: ${{ github.event.inputs.prompt }}
        run: |
          # cd executor (run from repo root)
          PYTHONPATH=executor python -m omae.cli -p playbooks/${{ github.event.inputs.pipeline }}.yaml
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Build site (if present)
        run: |
          if [ -f "site/package.json" ]; then cd site && npm install && npm run build && cd ..; else echo "No site/ to build"; fi
      - name: Prepare publish folders
        run: |
          mkdir -p apps/publish/current apps/publish/candidate apps/publish/releases
          if [ -d "site/dist" ]; then
            rm -rf apps/publish/candidate/* || true
            cp -R site/dist/* apps/publish/candidate/
          fi
      - name: Commit and push results
        run: |
          git config user.name "omae-bot"
          git config user.email "omae@example.com"
          git add -A
          git commit -m "OMAe run: ${{ github.event.inputs.pipeline }}" || echo "No changes"
          git push
