name: Build & Publish Studio (+ artifacts) to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            apps/studio/package-lock.json
            site/package-lock.json

      - name: Build Studio (Vite)
        working-directory: apps/studio
        run: |
          npm install
          npm run build

      - name: Copy published apps into Pages artifact
        run: |
          DIST="apps/studio/dist"
          mkdir -p "$DIST/apps/candidate" "$DIST/apps/current" "$DIST/releases"
          [ -d apps/publish/candidate ] && rsync -a apps/publish/candidate/ "$DIST/apps/candidate/" || true
          [ -d apps/publish/current ]   && rsync -a apps/publish/current/   "$DIST/apps/current/"   || true
          [ -d apps/publish/releases ]  && rsync -a apps/publish/releases/  "$DIST/releases/"       || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/studio/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
