name: Pages Build & Publish

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write
  workflows: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build the template the Studio uses (landing_saas)
      - name: Install & build landing
        working-directory: templates/landing_saas
        run: |
          npm ci || npm i
          npm run build

      # Publish to apps/publish/candidate
      - name: Publish candidate to repo
        run: |
          rm -rf apps/publish/candidate/*
          mkdir -p apps/publish/candidate
          cp -R templates/landing_saas/dist/. apps/publish/candidate/

          # Inject correct <base> for GH Pages path
          f=apps/publish/candidate/index.html
          p="/OMAE/${f%index.html}"
          awk -v base="$p" 'BEGIN{IGNORECASE=1} /<head[^>]*>/{print;print "  <base href=\"" base "\">";next} {print}' "$f" > "$f.tmp" && mv "$f.tmp" "$f"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "publish(candidate): update from workflow" || echo "nothing to commit"
          git push
